server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

app.auth.secret=${AUTH_SECRET:backend-secret-string}

app.stripe.secret-key=${STRIPE_SECRET_KEY:"sk_test_..."}
app.stripe.currency=${STRIPE_CURRENCY:"usd"}
app.client.base-url=${CLIENT_BASE_URL:"http://localhost:5173"}
